/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppOrdensServicoRouteImport } from './routes/_app/ordens-servico'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppOrdensServicoIndexRouteImport } from './routes/_app/ordens-servico/index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppOrdensServicoNovaRouteImport } from './routes/_app/ordens-servico/nova'
import { Route as AppOrdensServicoIdRouteImport } from './routes/_app/ordens-servico/$id'
import { Route as AppClientesNovoRouteImport } from './routes/_app/clientes/novo'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensServicoRoute = AppOrdensServicoRouteImport.update({
  id: '/ordens-servico',
  path: '/ordens-servico',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensServicoIndexRoute = AppOrdensServicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdensServicoRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppOrdensServicoNovaRoute = AppOrdensServicoNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppOrdensServicoRoute,
} as any)
const AppOrdensServicoIdRoute = AppOrdensServicoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdensServicoRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/ordens-servico': typeof AppOrdensServicoRouteWithChildren
  '/relatorios': typeof AppRelatoriosRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/ordens-servico/$id': typeof AppOrdensServicoIdRoute
  '/ordens-servico/nova': typeof AppOrdensServicoNovaRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/ordens-servico/': typeof AppOrdensServicoIndexRoute
}
export interface FileRoutesByTo {
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/ordens-servico/$id': typeof AppOrdensServicoIdRoute
  '/ordens-servico/nova': typeof AppOrdensServicoNovaRoute
  '/clientes': typeof AppClientesIndexRoute
  '/ordens-servico': typeof AppOrdensServicoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/ordens-servico': typeof AppOrdensServicoRouteWithChildren
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/ordens-servico/$id': typeof AppOrdensServicoIdRoute
  '/_app/ordens-servico/nova': typeof AppOrdensServicoNovaRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/ordens-servico/': typeof AppOrdensServicoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/ordens-servico'
    | '/relatorios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/ordens-servico/$id'
    | '/ordens-servico/nova'
    | '/clientes/'
    | '/ordens-servico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agenda'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/relatorios'
    | '/'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/ordens-servico/$id'
    | '/ordens-servico/nova'
    | '/clientes'
    | '/ordens-servico'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agenda'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/estoque'
    | '/_app/financeiro'
    | '/_app/ordens-servico'
    | '/_app/relatorios'
    | '/_app/'
    | '/_app/clientes/$id'
    | '/_app/clientes/novo'
    | '/_app/ordens-servico/$id'
    | '/_app/ordens-servico/nova'
    | '/_app/clientes/'
    | '/_app/ordens-servico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico': {
      id: '/_app/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof AppOrdensServicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico/': {
      id: '/_app/ordens-servico/'
      path: '/'
      fullPath: '/ordens-servico/'
      preLoaderRoute: typeof AppOrdensServicoIndexRouteImport
      parentRoute: typeof AppOrdensServicoRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/ordens-servico/nova': {
      id: '/_app/ordens-servico/nova'
      path: '/nova'
      fullPath: '/ordens-servico/nova'
      preLoaderRoute: typeof AppOrdensServicoNovaRouteImport
      parentRoute: typeof AppOrdensServicoRoute
    }
    '/_app/ordens-servico/$id': {
      id: '/_app/ordens-servico/$id'
      path: '/$id'
      fullPath: '/ordens-servico/$id'
      preLoaderRoute: typeof AppOrdensServicoIdRouteImport
      parentRoute: typeof AppOrdensServicoRoute
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppClientesNovoRoute: typeof AppClientesNovoRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
  AppClientesNovoRoute: AppClientesNovoRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppOrdensServicoRouteChildren {
  AppOrdensServicoIdRoute: typeof AppOrdensServicoIdRoute
  AppOrdensServicoNovaRoute: typeof AppOrdensServicoNovaRoute
  AppOrdensServicoIndexRoute: typeof AppOrdensServicoIndexRoute
}

const AppOrdensServicoRouteChildren: AppOrdensServicoRouteChildren = {
  AppOrdensServicoIdRoute: AppOrdensServicoIdRoute,
  AppOrdensServicoNovaRoute: AppOrdensServicoNovaRoute,
  AppOrdensServicoIndexRoute: AppOrdensServicoIndexRoute,
}

const AppOrdensServicoRouteWithChildren =
  AppOrdensServicoRoute._addFileChildren(AppOrdensServicoRouteChildren)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppOrdensServicoRoute: typeof AppOrdensServicoRouteWithChildren
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppOrdensServicoRoute: AppOrdensServicoRouteWithChildren,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
